name: test

on:
  workflow_call:

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --silent

      - name: Setup env variables
        run: |
          echo -e "google_client_id\ngoogle_client_secret" | ./setup_env.sh

      - name: Build
        run: |
          pnpm run build
